#pragma once
#include <Windows.h>
#include <winrt\windows.system.h>
#include <winrt\windows.web.ui.h>
#include <winrt\windows.web.ui.interop.h>
#include <winrt\windows.ui.xaml.controls.h>
#include <winrt\windows.foundation.h>
#include <winrt\windows.web.http.h>
#include <winrt\windows.web.http.headers.h>
#include <winrt\Windows.Storage.h>
#include <winrt\Windows.Storage.Streams.h>
#include <strsafe.h>
#include <Shlwapi.h>
